### ISSUE TITLE
Example replacements for placeholders

### ISSUE THREAD

**Issue by SirYwell** [KyoriPowered/adventure-webui#7]
When writing text with placeholders, one might want to see how it looks like with "real world" values. Replacing it in the input field directly is cumbersome, so it would be nice to have extra fields for placeholders where you can put actual values in (and e.g., a check box to enable replacement). Not sure how that can be integrated nicely though...

**Comment by MiniDigger** [comment]
maybe we can do this with #37, have a seperate page for templates where you can save those values, key/value style?
